#!/bin/bash
old=suiteAV-3.0
new=suiteAV-3.2
var=3.2
sed -i 's/'$old'/'$new'/g' suiteAV
sed -i 's/'$old'/'$new'/g' init/youtube
sed -i 's/'$old'/'$new'/g' init/update
sed -i 's/'$old'/'$new'/g' init/playlist
sed -i 's/'$old'/'$new'/g' init/packages
cat /dev/null > yt-ver
echo $var > version
git add --chmod=+x suiteAV
cd init
git add --chmod=+x youtube playlist update packages
cd ..
exit
