#!/bin/bash
var1=suiteAV-1.7
var2=suiteAV-1.8
sed -i 's/'$var1'/'$var2'/g' suiteAV
sed -i 's/'$var1'/'$var2'/g' init/lang/it/italiano
sed -i 's/'$var1'/'$var2'/g' init/lang/it/lib_it
sed -i 's/'$var1'/'$var2'/g' init/lang/it/update
sed -i 's/'$var1'/'$var2'/g' init/lang/en/english
sed -i 's/'$var1'/'$var2'/g' init/lang/en/lib_en
sed -i 's/'$var1'/'$var2'/g' init/lang/en/update
cat /dev/null > yt-ver
echo 1.8 > version
